/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/rightcave.ts" />
/// <reference path="../scenes/leftcave.ts" />
/// <reference path="../scenes/intro.ts" />
/// <reference path="../scenes/intro2.ts" />
/// <reference path="../scenes/intro3.ts" />
/// <reference path="../scenes/intro4.ts" />
/// <reference path="../scenes/game.ts" /> 
//# sourceMappingURL=_reference.js.map